### ISSUE TITLE
Erroneous space character added to front of all selectors

### ISSUE THREAD

**Issue by teddybradford** [geddski/csstyle#40]
csstyle, at least when used as a component of postcss, causes a space character to be appended to all selectors.

```css
body {
  color: red;
}
``

becomes

```css
 body {
  color: red;
}
```
